spring:
  application:
    name: database-modeling-tool
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    default-property-inclusion: non_null

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
  show-actuator: false
  group-configs:
    - group: 'database-modeling-api'
      display-name: 'Database Modeling API'
      paths-to-match: '/api/**'
      packages-to-scan: 'com.dbmodeling.presentation.controller'

# 공통 애플리케이션 설정
app:
  name: Database Modeling Tool
  version: 1.0.0
  description: MSSQL 데이터베이스 모델링 도구