spring:
  # 프로덕션 환경 데이터베이스 설정
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dbmodeling_prod}
    username: ${DB_USERNAME:dbmodeling_user}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:10}
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      
  # 프로덕션 환경 JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        generate_statistics: false
        jdbc:
          batch_size: 100
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        
  # 프로덕션 환경 Flyway 설정
  flyway:
    clean-disabled: true
    validate-on-migrate: true
    
# 로깅 설정
logging:
  level:
    root: WARN
    com.dbmodeling: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/dbmodeling-app.log
    max-size: 100MB
    max-history: 30
    
# 프로덕션 환경 애플리케이션 설정
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://dbmodeling.yourdomain.com}
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# 액추에이터 설정 (모니터링)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true