spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbmodeling_dev
    username: ${DB_USERNAME:dbmodeling}
    password: ${DB_PASSWORD:dbmodeling}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        jdbc:
          time_zone: UTC
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false

  sql:
    init:
      mode: never # 개발 환경에서는 DDL 자동 생성 사용

logging:
  level:
    com.dbmodeling: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/dbmodeling-dev.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,beans,mappings
  endpoint:
    health:
      show-details: always
      show-components: always

springdoc:
  swagger-ui:
    enabled: true
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    displayOperationId: true
  api-docs:
    enabled: true

app:
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:5173
      - http://127.0.0.1:3000
      - http://127.0.0.1:5173
  validation:
    enabled: true
    strict-mode: false
  export:
    max-file-size: 10MB
    temp-directory: ${java.io.tmpdir}/dbmodeling-exports