spring:
  # 개발 환경 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/dbmodeling_dev
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      leak-detection-threshold: 30000
      
  # 개발 환경 JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        
  # 개발 환경 Flyway 설정
  flyway:
    clean-disabled: false
    
# 로깅 설정
logging:
  level:
    root: INFO
    com.dbmodeling: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
# 개발 환경 애플리케이션 설정
app:
  cors:
    allowed-origins: http://localhost:3000, http://localhost:5173
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600